
# Import library and setting parameter

In [2]:
import numpy as np
import cv2

# new intrinsic matrix
nmtx = np.array([[801.43630024 , 0.0, 677.61858434], [0.0, 601.55416833, 393.17735366], [0.0, 0.0, 1.0]])
# four corner of badminton court in image coordinate system 
court2D = np.array([[499, 353], [785, 348], [21, 647], [1208, 614]])
# four corner of badminton court in world coordinate system (the middle net )
court3D = np.array([ [-3.05, 6.7, 0], [3.05, 6.7, 0], [-3.05, -6.7, 0], [3.05, -6.7, 0]])

# Using solvePnP to calculate rotation matrix and transformation matrix

In [3]:
ret, rvec, tvec = cv2.solvePnP(np.array(court3D,np.float32), np.array(court2D,np.float32), np.array(nmtx,np.float32),0,flags = cv2.SOLVEPNP_ITERATIVE)

T = np.array(tvec,np.float32)
R = np.array(cv2.Rodrigues(rvec)[0],np.float32)
Rt = np.zeros((3,4))
Rt[:,:3] = R
Rt[:,3] = T[:,0]

print(Rt)


[[ 0.99917322 -0.03700627 -0.0168335  -0.49927494]
 [-0.0243279  -0.21250036 -0.97685808  0.20113543]
 [ 0.03257275  0.97645998 -0.21322496 10.66771889]]
